export type ServiceData = {
  slug: string;
  title: string;
  tagline: string;
  description: string;
  category: string;
  benefits: string[];
  features: { title: string; desc: string }[];
  process: { step: string; title: string; desc: string }[];
  faqs: { q: string; a: string }[];
};

export const SERVICES: ServiceData[] = [
  {
    slug: "seo",
    title: "SEO Services",
    tagline: "Rank higher. Get found. Grow faster.",
    category: "Digital Marketing",
    description:
      "Data-driven SEO that drives qualified organic traffic, builds authority, and compounds revenue month over month.",
    benefits: [
      "Higher Google rankings for revenue keywords",
      "Sustainable, compounding organic traffic",
      "Better lead quality and lower CAC",
      "Technical site health and Core Web Vitals fixes",
    ],
    features: [
      { title: "Technical SEO Audit", desc: "Crawl, indexing, speed, schema, and architecture review." },
      { title: "Keyword Strategy", desc: "Intent-mapped clusters tied to revenue goals." },
      { title: "On-Page Optimization", desc: "Content, metadata, internal links, and entity SEO." },
      { title: "Authority Building", desc: "White-hat link acquisition and digital PR." },
      { title: "Local SEO", desc: "GBP optimization, citations, and local landing pages." },
      { title: "Reporting", desc: "Transparent dashboards with rankings, traffic, and revenue." },
    ],
    process: [
      { step: "01", title: "Audit", desc: "We benchmark your site, competitors, and opportunities." },
      { step: "02", title: "Strategy", desc: "A 90-day roadmap mapped to business outcomes." },
      { step: "03", title: "Execute", desc: "Technical fixes, content, and link building in sprints." },
      { step: "04", title: "Scale", desc: "Double down on what's working with monthly reviews." },
    ],
    faqs: [
      { q: "How long until I see results?", a: "Early wins in 60–90 days, compounding growth from month 4 onward." },
      { q: "Do you guarantee rankings?", a: "No one credible does. We guarantee process, transparency, and effort." },
      { q: "Which industries do you cover?", a: "Real estate, e-commerce, SaaS, healthcare, EV, construction and more." },
    ],
  },
  {
    slug: "social-media-marketing",
    title: "Social Media Marketing",
    tagline: "Build a brand people follow, trust, and buy from.",
    category: "Digital Marketing",
    description:
      "Strategy, content, community, and performance — a full-stack social presence across Instagram, LinkedIn, YouTube and more.",
    benefits: ["Consistent brand presence", "Engaged community", "Higher inbound leads", "Stronger brand recall"],
    features: [
      { title: "Content Strategy", desc: "Pillars, formats, and posting cadence built around your audience." },
      { title: "Creative Production", desc: "Reels, carousels, photography, and motion graphics in-house." },
      { title: "Community Management", desc: "DM, comment, and reputation handling 7 days a week." },
      { title: "Performance Reporting", desc: "Reach, engagement, and conversion analytics monthly." },
    ],
    process: [
      { step: "01", title: "Brand Audit", desc: "We study your voice, audience, and competitors." },
      { step: "02", title: "Content Plan", desc: "Monthly calendar with hooks, scripts, and visuals." },
      { step: "03", title: "Publish", desc: "Daily execution across chosen platforms." },
      { step: "04", title: "Optimize", desc: "Analytics-driven iteration every 30 days." },
    ],
    faqs: [
      { q: "Which platforms do you manage?", a: "Instagram, Facebook, LinkedIn, YouTube, X, Threads, Pinterest." },
      { q: "Do you shoot original content?", a: "Yes — we run on-location shoots and produce reels in-studio." },
    ],
  },
  {
    slug: "google-ads",
    title: "Google Ads Management",
    tagline: "High-intent traffic that converts.",
    category: "Performance Marketing",
    description: "Search, Display, Shopping, YouTube and PMax campaigns engineered for ROAS, not vanity metrics.",
    benefits: ["Predictable lead flow", "Lower cost-per-acquisition", "Full-funnel attribution", "Daily optimization"],
    features: [
      { title: "Campaign Architecture", desc: "Tightly themed ad groups for max Quality Score." },
      { title: "Conversion Tracking", desc: "GA4, GTM, server-side and offline conversions wired correctly." },
      { title: "Creative & Copy", desc: "A/B-tested ad copy, RSAs, and shopping feeds." },
      { title: "Bid Strategy", desc: "Smart bidding tuned weekly against real margin data." },
    ],
    process: [
      { step: "01", title: "Account Audit", desc: "We find leaks, wasted spend, and opportunities." },
      { step: "02", title: "Build", desc: "New structure, tracking, creatives, and landing pages." },
      { step: "03", title: "Launch", desc: "Phased rollout with strict budget guardrails." },
      { step: "04", title: "Scale", desc: "Weekly optimization and budget reallocation." },
    ],
    faqs: [
      { q: "What's the minimum ad spend?", a: "We recommend ₹50,000+/month for meaningful learnings." },
      { q: "Do you charge a % of spend?", a: "We offer flat monthly retainers — no incentive to inflate spend." },
    ],
  },
  {
    slug: "meta-ads",
    title: "Meta Ads Management",
    tagline: "Facebook & Instagram ads that print pipeline.",
    category: "Performance Marketing",
    description: "Creative-led Meta advertising for D2C, services, lead gen and app installs.",
    benefits: ["Lower CPL", "Higher ROAS", "Scroll-stopping creatives", "Funnel-aware audiences"],
    features: [
      { title: "Audience Strategy", desc: "Lookalikes, interests, and retargeting layered intelligently." },
      { title: "Creative Studio", desc: "Static, video, UGC, and reels — fresh every month." },
      { title: "Pixel & CAPI Setup", desc: "iOS 14+ resilient tracking with Conversions API." },
      { title: "Funnel Building", desc: "TOFU/MOFU/BOFU campaigns mapped to the buyer journey." },
    ],
    process: [
      { step: "01", title: "Discovery", desc: "Offer, audience, and creative brief workshop." },
      { step: "02", title: "Build", desc: "Pixel, CAPI, campaigns, and creative batch 1." },
      { step: "03", title: "Test", desc: "Rapid creative testing to find winners." },
      { step: "04", title: "Scale", desc: "Scale winners with budget and creative variants." },
    ],
    faqs: [
      { q: "Do you produce creatives?", a: "Yes — fresh statics and reels each month are included." },
    ],
  },
  {
    slug: "performance-marketing",
    title: "Performance Marketing",
    tagline: "Every rupee accountable. Every channel measured.",
    category: "Performance Marketing",
    description: "Full-funnel performance across Google, Meta, LinkedIn, YouTube, and programmatic — unified under one dashboard.",
    benefits: ["Unified attribution", "Lower blended CAC", "Faster experimentation", "Channel diversification"],
    features: [
      { title: "Multi-Channel Strategy", desc: "Channel mix tuned to your funnel and margin." },
      { title: "Unified Dashboarding", desc: "Looker Studio dashboards for the whole team." },
      { title: "Experimentation", desc: "Weekly tests on creative, audience and landing pages." },
      { title: "Landing Page CRO", desc: "Higher conversion rates without more spend." },
    ],
    process: [
      { step: "01", title: "Audit", desc: "Spend, channels, and attribution review." },
      { step: "02", title: "Plan", desc: "Quarterly growth plan with clear KPIs." },
      { step: "03", title: "Execute", desc: "Cross-channel campaigns and creative output." },
      { step: "04", title: "Scale", desc: "Reallocate budget to the highest ROAS channels." },
    ],
    faqs: [{ q: "Do you work with startups?", a: "Yes — from seed to Series B and beyond." }],
  },
  {
    slug: "website-development",
    title: "Website Development",
    tagline: "Fast, beautiful, conversion-focused websites.",
    category: "Web Development",
    description: "Custom websites built on modern stacks — designed to rank, convert, and scale with your business.",
    benefits: ["Blazing fast performance", "SEO-ready architecture", "Mobile-first design", "CMS for non-devs"],
    features: [
      { title: "Custom UI/UX", desc: "Bespoke design tailored to your brand." },
      { title: "Headless or Traditional CMS", desc: "WordPress, Sanity, Strapi or custom admin panels." },
      { title: "Performance Engineering", desc: "100 Lighthouse scores, lazy loading, edge delivery." },
      { title: "SEO Foundations", desc: "Schema, sitemaps, semantic HTML, OG tags." },
    ],
    process: [
      { step: "01", title: "Discovery", desc: "Goals, audience, and content workshop." },
      { step: "02", title: "Design", desc: "Wireframes → high-fidelity Figma designs." },
      { step: "03", title: "Build", desc: "Sprint-based development with weekly demos." },
      { step: "04", title: "Launch", desc: "QA, migration, and post-launch monitoring." },
    ],
    faqs: [
      { q: "How long does a website take?", a: "4–10 weeks depending on scope and content readiness." },
      { q: "Do you offer maintenance?", a: "Yes — monthly care plans available." },
    ],
  },
  {
    slug: "shopify-development",
    title: "Shopify Development",
    tagline: "High-converting Shopify stores that scale.",
    category: "Web Development",
    description: "Custom Shopify and Shopify Plus stores — themes, apps, and headless storefronts.",
    benefits: ["Higher conversion rate", "Custom theme matching brand", "App integrations", "Shopify Plus expertise"],
    features: [
      { title: "Custom Theme Development", desc: "Pixel-perfect, fast-loading themes." },
      { title: "App Integration", desc: "Klaviyo, Yotpo, ReCharge, Gorgias and more." },
      { title: "Shopify Plus", desc: "Scripts, Flow, Functions, B2B and Markets." },
      { title: "Migration", desc: "Move from WooCommerce, Magento or Wix safely." },
    ],
    process: [
      { step: "01", title: "Brief", desc: "Brand, catalog, and conversion goals." },
      { step: "02", title: "Design", desc: "Storefront design and product detail page UX." },
      { step: "03", title: "Build", desc: "Theme development, apps, and content load." },
      { step: "04", title: "Launch", desc: "QA, payment setup, and go-live." },
    ],
    faqs: [{ q: "Do you build Shopify apps?", a: "Yes — custom private and public Shopify apps." }],
  },
  {
    slug: "wordpress-development",
    title: "WordPress Development",
    tagline: "Powerful WordPress sites — fast, secure, and SEO-ready.",
    category: "Web Development",
    description: "Custom WordPress development, WooCommerce, and managed hosting for content-heavy sites.",
    benefits: ["Easy content editing", "SEO friendly", "Scalable hosting", "Plugin-light builds"],
    features: [
      { title: "Custom Themes", desc: "No bloated page builders — hand-coded performance." },
      { title: "WooCommerce", desc: "Custom checkout, payment gateways and product UX." },
      { title: "Security & Speed", desc: "Hardening, caching, CDN, image optimization." },
      { title: "Multilingual", desc: "WPML/Polylang setups for global audiences." },
    ],
    process: [
      { step: "01", title: "Plan", desc: "IA, content model, and plugin selection." },
      { step: "02", title: "Design", desc: "Figma designs and component library." },
      { step: "03", title: "Build", desc: "Custom theme + ACF blocks." },
      { step: "04", title: "Optimize", desc: "Performance, security, and SEO finalization." },
    ],
    faqs: [{ q: "Will I be able to edit pages?", a: "Yes — custom editor blocks built for your team." }],
  },
  {
    slug: "laravel-development",
    title: "Laravel Development",
    tagline: "Robust Laravel applications for serious products.",
    category: "Web Development",
    description: "Laravel-powered SaaS, marketplaces, admin panels, and APIs — built for scale and maintainability.",
    benefits: ["Battle-tested framework", "Clean architecture", "Easy to maintain", "Scales to millions"],
    features: [
      { title: "Custom SaaS", desc: "Multi-tenant SaaS with billing and roles." },
      { title: "APIs", desc: "REST and GraphQL APIs with authentication and rate limits." },
      { title: "Admin Panels", desc: "Filament/Nova powered dashboards." },
      { title: "Integrations", desc: "Stripe, Razorpay, Twilio, SendGrid and more." },
    ],
    process: [
      { step: "01", title: "Discovery", desc: "Product workshop and tech architecture." },
      { step: "02", title: "Architecture", desc: "Schema, modules, and deployment plan." },
      { step: "03", title: "Build", desc: "Agile sprints with weekly demos." },
      { step: "04", title: "Deploy", desc: "CI/CD, monitoring, and hand-off." },
    ],
    faqs: [{ q: "Do you maintain Laravel apps post-launch?", a: "Yes — dedicated retainer plans available." }],
  },
  {
    slug: "react-development",
    title: "React Development",
    tagline: "Modern React apps and dashboards that feel native.",
    category: "Web Development",
    description: "Next.js, Vite, and React Native — production-grade frontends, dashboards, and SPAs.",
    benefits: ["Native-feeling UX", "Reusable component systems", "SSR & SEO ready", "Real-time features"],
    features: [
      { title: "Next.js Apps", desc: "SSR/ISR/SSG, app router, and server actions." },
      { title: "Design Systems", desc: "Storybook-driven component libraries." },
      { title: "Realtime", desc: "WebSockets, Pusher, Supabase realtime." },
      { title: "Testing", desc: "Vitest, Playwright, and CI pipelines." },
    ],
    process: [
      { step: "01", title: "Discover", desc: "Requirements and design tokens." },
      { step: "02", title: "Architect", desc: "Routing, state, and data layer." },
      { step: "03", title: "Build", desc: "Component-by-component delivery." },
      { step: "04", title: "Ship", desc: "Deploy on Vercel/Cloudflare/AWS." },
    ],
    faqs: [{ q: "Do you do React Native?", a: "Yes — universal apps with Expo and bare RN." }],
  },
  {
    slug: "mobile-app-development",
    title: "Mobile App Development",
    tagline: "iOS & Android apps users love.",
    category: "Mobile",
    description: "Native and cross-platform mobile apps for startups and enterprises — from MVP to scale.",
    benefits: ["Native performance", "Faster time-to-market", "App Store optimization", "Crash-free experience"],
    features: [
      { title: "Native iOS / Android", desc: "Swift and Kotlin for performance-critical apps." },
      { title: "Cross-Platform", desc: "Flutter and React Native for faster shipping." },
      { title: "Backend", desc: "Firebase, Supabase, or custom Node/Laravel APIs." },
      { title: "App Store Launch", desc: "ASO, screenshots, store listings, and reviews." },
    ],
    process: [
      { step: "01", title: "Product Strategy", desc: "MVP scope and feature prioritization." },
      { step: "02", title: "UX Design", desc: "Flows, wireframes, and Figma prototypes." },
      { step: "03", title: "Build", desc: "2-week sprints with TestFlight/Internal Testing builds." },
      { step: "04", title: "Launch", desc: "Store submission and post-launch analytics." },
    ],
    faqs: [{ q: "iOS, Android, or both?", a: "We help you decide based on audience and budget." }],
  },
  {
    slug: "flutter-development",
    title: "Flutter App Development",
    tagline: "One codebase. iOS, Android, web.",
    category: "Mobile",
    description: "Beautiful, performant Flutter apps that ship faster and look native on every platform.",
    benefits: ["Single codebase", "Faster MVP", "Beautiful UI", "Lower cost"],
    features: [
      { title: "Custom UI", desc: "Pixel-perfect screens with smooth 60fps animations." },
      { title: "State Management", desc: "Riverpod, Bloc, or Provider — picked for your scale." },
      { title: "Integrations", desc: "Payment, maps, push, analytics, and more." },
      { title: "CI/CD", desc: "Codemagic / Fastlane pipelines to App Store and Play." },
    ],
    process: [
      { step: "01", title: "Scope", desc: "Feature definition and tech approach." },
      { step: "02", title: "Design", desc: "Material 3 / Cupertino design system." },
      { step: "03", title: "Build", desc: "Sprint-based with weekly TestFlight builds." },
      { step: "04", title: "Launch", desc: "Store submissions and analytics setup." },
    ],
    faqs: [{ q: "Is Flutter ready for production?", a: "Yes — used by Google, BMW, eBay and many more." }],
  },
  {
    slug: "ui-ux-design",
    title: "UI/UX Design",
    tagline: "Interfaces that delight and convert.",
    category: "Design",
    description: "Research-led product design — wireframes, prototypes, and design systems for web and mobile.",
    benefits: ["Higher conversion", "Better usability", "Design system for scale", "Faster dev hand-off"],
    features: [
      { title: "User Research", desc: "Interviews, surveys, and competitor analysis." },
      { title: "Wireframing", desc: "Low-fi flows validated before high-fi design." },
      { title: "High-Fidelity Design", desc: "Pixel-perfect Figma designs." },
      { title: "Design Systems", desc: "Reusable tokens, components, and documentation." },
    ],
    process: [
      { step: "01", title: "Research", desc: "Understand users, goals, and constraints." },
      { step: "02", title: "Wireframe", desc: "Flows and low-fi layouts." },
      { step: "03", title: "Design", desc: "Hi-fi UI, prototype, and design system." },
      { step: "04", title: "Hand-off", desc: "Specs, tokens, and dev support." },
    ],
    faqs: [{ q: "Do you build what you design?", a: "Yes — seamless design-to-dev under one roof." }],
  },
  {
    slug: "branding",
    title: "Branding Services",
    tagline: "Brands people remember, prefer, and pay more for.",
    category: "Design",
    description: "Strategy, identity, and brand systems — the full toolkit to look and feel like a category leader.",
    benefits: ["Distinct identity", "Premium positioning", "Brand consistency", "Higher trust"],
    features: [
      { title: "Brand Strategy", desc: "Purpose, positioning, and personality." },
      { title: "Identity", desc: "Logo, color, typography, and iconography." },
      { title: "Guidelines", desc: "A complete brand book your whole team can use." },
      { title: "Brand Collateral", desc: "Stationery, decks, social templates, packaging." },
    ],
    process: [
      { step: "01", title: "Discover", desc: "Audience, competitors, and ambition." },
      { step: "02", title: "Define", desc: "Strategy, positioning, and messaging." },
      { step: "03", title: "Design", desc: "Identity system and applications." },
      { step: "04", title: "Deliver", desc: "Brand book and rollout assets." },
    ],
    faqs: [{ q: "Do you do rebrands?", a: "Yes — from refresh to full repositioning." }],
  },
  {
    slug: "logo-design",
    title: "Logo Design",
    tagline: "A logo that earns its place on the storefront.",
    category: "Design",
    description: "Considered logo design rooted in strategy — not trends. Built to last decades.",
    benefits: ["Timeless mark", "Scalable across mediums", "Files for every use case", "Strategic rationale"],
    features: [
      { title: "Discovery", desc: "Brand essence, competitors, and inspiration." },
      { title: "Concepts", desc: "3 strong directions to choose from." },
      { title: "Refinement", desc: "Iterations until it's perfect." },
      { title: "Delivery", desc: "Vector, raster, light, dark, lockups, favicon." },
    ],
    process: [
      { step: "01", title: "Brief", desc: "Inputs and references." },
      { step: "02", title: "Sketch", desc: "Concept exploration." },
      { step: "03", title: "Design", desc: "3 polished directions." },
      { step: "04", title: "Final", desc: "Refinement and full asset pack." },
    ],
    faqs: [{ q: "How many revisions?", a: "Unlimited within the chosen direction." }],
  },
  {
    slug: "content-marketing",
    title: "Content Marketing",
    tagline: "Content that ranks, educates, and converts.",
    category: "Digital Marketing",
    description: "SEO-led blogs, thought leadership, video scripts, and lead magnets that build authority and pipeline.",
    benefits: ["Organic traffic", "Authority building", "Lead generation", "Sales enablement"],
    features: [
      { title: "Content Strategy", desc: "Topic clusters mapped to buyer journey." },
      { title: "SEO Writing", desc: "Long-form, expert-led, and search-optimized." },
      { title: "Video Scripting", desc: "YouTube and short-form scripts." },
      { title: "Lead Magnets", desc: "Ebooks, templates, and gated assets." },
    ],
    process: [
      { step: "01", title: "Research", desc: "Audience and keyword research." },
      { step: "02", title: "Plan", desc: "Monthly editorial calendar." },
      { step: "03", title: "Create", desc: "Writers, editors, designers in sync." },
      { step: "04", title: "Distribute", desc: "SEO, social, and email distribution." },
    ],
    faqs: [{ q: "How many articles per month?", a: "Plans from 4 to 30+ articles monthly." }],
  },
  {
    slug: "influencer-marketing",
    title: "Influencer Marketing",
    tagline: "Authentic voices. Measurable impact.",
    category: "PR & Media",
    description: "End-to-end influencer campaigns — discovery, outreach, briefing, contracts, content, and reporting.",
    benefits: ["Trusted reach", "UGC at scale", "Measurable ROI", "Vetted creators"],
    features: [
      { title: "Creator Discovery", desc: "Data-backed shortlists across micro to mega." },
      { title: "Outreach & Contracts", desc: "Negotiation, paperwork, and rights handled." },
      { title: "Content Briefing", desc: "Briefs that protect brand and unlock creativity." },
      { title: "Reporting", desc: "Reach, engagement, and conversion tracking." },
    ],
    process: [
      { step: "01", title: "Strategy", desc: "Audience and creator-type fit." },
      { step: "02", title: "Discovery", desc: "Shortlist and vet creators." },
      { step: "03", title: "Activate", desc: "Brief, produce, and publish." },
      { step: "04", title: "Report", desc: "Performance dashboards and learnings." },
    ],
    faqs: [{ q: "Do you work with celebrities?", a: "Yes — from nano-creators to A-list celebrities." }],
  },
  {
    slug: "pr-services",
    title: "PR Services",
    tagline: "Be the story journalists want to tell.",
    category: "PR & Media",
    description: "Strategic PR, media outreach, founder branding, and crisis comms across India and global markets.",
    benefits: ["Top-tier media coverage", "Founder thought leadership", "Crisis preparedness", "Brand authority"],
    features: [
      { title: "Media Relations", desc: "Active relationships across business and tech press." },
      { title: "Founder Branding", desc: "LinkedIn, podcasts, op-eds, and keynotes." },
      { title: "Press Releases", desc: "Newsworthy storytelling and distribution." },
      { title: "Crisis Comms", desc: "Rapid-response playbooks and on-call support." },
    ],
    process: [
      { step: "01", title: "Audit", desc: "Story angles and media targets." },
      { step: "02", title: "Plan", desc: "Quarterly PR roadmap." },
      { step: "03", title: "Pitch", desc: "Targeted outreach to journalists." },
      { step: "04", title: "Measure", desc: "Coverage, share-of-voice, and sentiment." },
    ],
    faqs: [{ q: "Can you guarantee coverage?", a: "Quality PR earns coverage — we guarantee process and effort." }],
  },
  {
    slug: "ecommerce-marketing",
    title: "E-commerce Marketing",
    tagline: "More traffic. More AOV. More repeat buyers.",
    category: "Digital Marketing",
    description: "End-to-end growth for D2C and online stores — paid, email, SMS, SEO, CRO, and retention.",
    benefits: ["Higher ROAS", "Lower CAC", "Better LTV", "Predictable revenue"],
    features: [
      { title: "Paid Acquisition", desc: "Meta, Google, and TikTok ads tuned to ROAS." },
      { title: "Email & SMS", desc: "Klaviyo flows, campaigns, and segmentation." },
      { title: "CRO", desc: "PDP, cart, and checkout optimization." },
      { title: "Retention", desc: "Loyalty, reviews, and subscription strategy." },
    ],
    process: [
      { step: "01", title: "Audit", desc: "Funnel, creative, and data review." },
      { step: "02", title: "Plan", desc: "Channel mix and 90-day roadmap." },
      { step: "03", title: "Execute", desc: "Daily campaigns and creatives." },
      { step: "04", title: "Scale", desc: "Reinvest in winners month over month." },
    ],
    faqs: [{ q: "Do you work with Shopify only?", a: "Shopify, WooCommerce, Magento, and custom stacks." }],
  },
  {
    slug: "lead-generation",
    title: "Lead Generation Services",
    tagline: "Qualified leads, on tap.",
    category: "Performance Marketing",
    description: "B2B and B2C lead-gen systems combining paid media, landing pages, CRM, and nurture flows.",
    benefits: ["Predictable pipeline", "Lower cost per lead", "Sales-ready leads", "Full CRM integration"],
    features: [
      { title: "Landing Pages", desc: "Built and CRO-tested for the offer." },
      { title: "Paid Funnels", desc: "Meta, Google, LinkedIn lead-gen campaigns." },
      { title: "CRM & Nurture", desc: "HubSpot/Zoho integration with email & WhatsApp nurture." },
      { title: "Reporting", desc: "Lead quality and pipeline dashboards." },
    ],
    process: [
      { step: "01", title: "Offer", desc: "Define irresistible offer and ICP." },
      { step: "02", title: "Build", desc: "Landing, tracking, and CRM." },
      { step: "03", title: "Launch", desc: "Multi-channel paid campaigns." },
      { step: "04", title: "Optimize", desc: "Lower CPL, raise quality." },
    ],
    faqs: [{ q: "Do you guarantee leads?", a: "We commit to KPIs after a 30-day learning period." }],
  },
];

export const INDUSTRIES = [
  { slug: "construction", name: "Construction", desc: "Marketing for builders, contractors, and infra firms." },
  { slug: "interior-design", name: "Interior Design", desc: "Visual-first marketing for studios and designers." },
  { slug: "healthcare", name: "Healthcare", desc: "Compliant patient acquisition for clinics and hospitals." },
  { slug: "real-estate", name: "Real Estate", desc: "Lead-gen for builders, brokers, and property platforms." },
  { slug: "travel", name: "Travel", desc: "Bookings and brand for tour operators and DMCs." },
  { slug: "ecommerce", name: "E-commerce", desc: "Full-funnel growth for D2C and online retail." },
  { slug: "manufacturing", name: "Manufacturing", desc: "B2B lead-gen and brand for OEMs and suppliers." },
  { slug: "education", name: "Education", desc: "Admissions marketing for schools, ed-tech, and coaching." },
  { slug: "ev", name: "EV Industry", desc: "Brand and demand for EV makers and charging networks." },
  { slug: "finance", name: "Finance", desc: "Trust-led marketing for fintech, advisory, and lending." },
];

export const CLIENTS = ["Google", "Meta", "Shopify", "Amazon", "Microsoft", "Adobe", "HubSpot", "Salesforce", "Zoho", "WordPress"];

export const STATS = [
  { value: "500+", label: "Projects Delivered" },
  { value: "100+", label: "Happy Clients" },
  { value: "12+", label: "Industries Served" },
  { value: "95%", label: "Client Retention" },
];

export const SERVICE_CATEGORIES = [
  "Digital Marketing",
  "Web Development",
  "Mobile",
  "Design",
  "Performance Marketing",
  "PR & Media",
];
